### PR TITLE
Plot maps of past performance

### PR DESCRIPTION
**Pull request by geek-yang**
Prepare maps for the "past performance" page in cpm analysis. The workflow includes:
- preprocess cpm/rcm/gcm data and regridding
- calculate the difference between model simulations and observations
- Map clipping based on the regions of interest and plot maps of each region
- Display these maps in cpm page and use dropdown menu for selections

The data is provided by Petter Lind.

### CODE REVIEW

**Comment by geek-yang** [comment]
The duplication reported by sonarcloud is due to the dropdown menu in the `.vue` file which creates `past performance`. The dropdown is only used for review the maps and will be changed to adapt to our [new design](https://nlesc.sharepoint.com/:p:/s/EUCP/EUUwbo_bb1NOleak7eRVtscBku5gt109L8HMg8Mk6ng-0Q?e=akHbNo) later. Therefore, I would suggest we ignore this check for now.

**Comment by geek-yang** [comment]
There is a new issue #41 related to this PR. We need to decide the best naming convention for the maps we used in `past performance`  `future change`  `Analyse` tabs in cpm page. Currently we have two naming systems for the maps (one follows the naming convention based on Petter Lind's data and the other follows the naming convention based on Tom's data).

Note that some maps can not be shown due to the fact that they have different names in different regions and the current implementation of dropdown menu cannot handle alternatives (e.g. ETHZ maps in region `AL` is `ethz-cclm_mpi`, while in region `NW` is `ethz-cclm_ecmwf-erai`). It is not fixed in this PR since it also corresponds to the filtering of models in dropdown list based on the regions.

I would like to suggest we address the naming issue #41 together with issue #37 .

**Comment by geek-yang** [comment]
When reviewing this PR, please get this branch and deploy it locally. Then check the maps under the tag `Past performance` in the CPM page. Just too many maps and it is too difficult for the `Files changed` feature on this page to handle this.

**Review by Peter9192 — APPROVED** [review]
Approving, will leave comments in new issue

**Pull request merged**
