### PR TITLE
Cpm in context 

### PR DESCRIPTION
**Pull request by Peter9192**
Formerly known as "lines of evidence"

### CODE REVIEW

**Comment by Peter9192** [comment]
Yang, would you be able to do a review of this? There's more to do, but I want to wrap up a few more things before the holidays, so I think I'll leave it at this.

**Review by geek-yang — APPROVED** [review]
@Peter9192 Excellent! Looks super awesome! And very clean implementation. Maybe later on we want to add some notes about the points got highlighted in the panel after clicking (just let user know what they see after clicking). But I guess it is not something planned in this PR and it is already QUITE good to go. Just merge it!

**Comment by geek-yang** [comment]
And the plot is not changing after choosing different regions. But I think that's what we expect for now, I assume. And we will possibly update it in next PR.

**Comment by Peter9192** [comment]
Thanks for the review. Indeed, we still want to update the plot based on the selected region, season, and perhaps make it possible to select variables as well.

**Pull request merged**
