### PR TITLE
Update the default model option when selecting a different region

### LINKED ISSUE #56: Hiding "impossible" models when navigating between regions
Following the discussion in #51, it would be good to implement this. At the moment, a user can find "impossible" results by selecting a combination of model/season/etc, then moving to another region that this model does/should not show. When starting at this region, the model does not appear in the dropdown. However, when moving towards that region with the selection already made, the results show anyway. Sometimes the CPM image is missing. Sometimes it is not. In either of those situations, there should be a clear result showing that this model does not work for the selected region.

### PR DESCRIPTION
**Pull request by geek-yang**
This PR fixes #56 .

### CODE REVIEW

**Review by bvreede — COMMENTED** [review]
Looks good! It would be nice however to keep the selection of the model if this is possible. It is good that now an impossible combination no longer shows up, but if the combination region/model is possible, it would be nice not to lose the selected model when moving to another region.

**Comment by geek-yang** [comment]
> Looks good! It would be nice however to keep the selection of the model if this is possible. It is good that now an impossible combination no longer shows up, but if the combination region/model is possible, it would be nice not to lose the selected model when moving to another region.

Thanks for your comment @bvreede. Very good point! It is implemented now.

**Comment by bvreede** [comment]
It's not working on my end... maybe we can look at it tomorrow at the office!

**Comment by geek-yang** [comment]
> It's not working on my end... maybe we can look at it tomorrow at the office!

Thanks for your review again. This is weird. It works on my machine. Let's take a look together tomorrow.

**Review by bvreede — APPROVED** [review]
OK it works now, magic! :)

**Pull request merged**
